version: '3'
services:
  zerologgrpcprovider:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1"
        NODE_VERSION: "16"
    network_mode: host
    environment:
      GOPRIVATE: ${GOPRIVATE}
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
